[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
authors = ["Davis Raymond Muro <davis.ray.muro@gmail.com>"]
description = "A networked key-value store"
license = "MIT"

[[bin]]
name = "kvs"
test = false

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
